# Form implementation generated from reading ui file 'c:\Users\student\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\super_duper_point_mover\super_duper_point_mover_dialog_base.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SuperDuperPointMoverDialogBase(object):
    def setupUi(self, SuperDuperPointMoverDialogBase):
        SuperDuperPointMoverDialogBase.setObjectName("SuperDuperPointMoverDialogBase")
        SuperDuperPointMoverDialogBase.resize(319, 337)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SuperDuperPointMoverDialogBase)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(SuperDuperPointMoverDialogBase)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.layerComboBox = QtWidgets.QComboBox(SuperDuperPointMoverDialogBase)
        self.layerComboBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.layerComboBox.setObjectName("layerComboBox")
        self.verticalLayout.addWidget(self.layerComboBox)
        self.pushButton = QtWidgets.QPushButton(SuperDuperPointMoverDialogBase)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.button_box = QtWidgets.QDialogButtonBox(SuperDuperPointMoverDialogBase)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout_2.addWidget(self.button_box)

        self.retranslateUi(SuperDuperPointMoverDialogBase)
        self.button_box.accepted.connect(SuperDuperPointMoverDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(SuperDuperPointMoverDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SuperDuperPointMoverDialogBase)

    def retranslateUi(self, SuperDuperPointMoverDialogBase):
        _translate = QtCore.QCoreApplication.translate
        SuperDuperPointMoverDialogBase.setWindowTitle(_translate("SuperDuperPointMoverDialogBase", "Super Duper Point Mover"))
        self.label.setText(_translate("SuperDuperPointMoverDialogBase", "Выбор слоя:"))
        self.pushButton.setText(_translate("SuperDuperPointMoverDialogBase", "Настроить геометрию"))
