version: '3.1'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: '1234'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
